# Generated by Django 2.2.7 on 2020-04-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=255, verbose_name='session id')),
                ('history', models.CharField(max_length=255, verbose_name='计算历史')),
            ],
        ),
    ]
